# Generated by Django 3.1.3 on 2020-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_auto_20201130_1944"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
